### PR TITLE
Release 1.6.2

### PR DESCRIPTION
**Pull request by jakirkham**
Update to the 1.6.2 release of XGBoost.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
Are there any additional commits/merges that need to be made to https://github.com/rapidsai/xgboost/tree/branch-22.10 for `1.6.2`?

If not, I can merge this, update the Jenkins job accordingly, and run a build.

**Comment by jakirkham** [comment]
Don't think so. The previous changes that were in 22.06 were tested very close to, but not quite including this tag.

Running CI to confirm we are not missing anything would be helpful.

cc @hcho3 @trivialfis (in case either of you have thoughts here on this change)

**Comment by hcho3** [comment]
No, it should be sufficient to use the 1.6.2 tag as it is.

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/rapidsai/integration/pull/529 ) to update the `xgboost` package version used in RAPIDS to 1.6.2 as well

**Pull request merged**
