### PR TITLE
Update build flags

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR updates the `CMAKE_CXX_STANDARD` build flag for building `xgboost` to align with the version required by `rmm`, which is a dependency of `xgboost`.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
Awaiting review from @trivialfis before merging. Jiaming, is this change okay?

**Review by trivialfis — APPROVED** [review]
Thanks for the update,  if it doesn't work you can patch https://github.com/dmlc/xgboost/blob/05497a91419e35ee915f0811c475c853882c0a8f/cmake/Utils.cmake#L171 .

**Comment by trivialfis** [comment]
also this https://github.com/dmlc/xgboost/blob/05497a91419e35ee915f0811c475c853882c0a8f/cmake/Utils.cmake#L191 .

**Comment by ajschmidt8** [comment]
@trivialfis , opened a PR with the above changes here: https://github.com/rapidsai/xgboost/pull/36

**Pull request merged**
